#!/usr/bin/env python

from twisted.python import usage, log
from twisted.internet import reactor, defer

from sgas.client import config, commands, util



def main():

    cfg = config.URUpdateOptions()
    cfg.parseOptions()

    return commands.updateUsageRecords(cfg['url'])



if __name__ == '__main__':
    reactor.callWhenRunning(util.wrapMain, main)
    reactor.run()

