#!/usr/bin/env python

from twisted.internet import reactor

from sgasclient import config, commands, util



def main():

    cfg = config.URUpdateOptions()
    cfg.parseOptions()

    return commands.updateUsageRecords(cfg['url'])



if __name__ == '__main__':
    reactor.callWhenRunning(util.wrapMain, main)
    reactor.run()

